/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   INTRO.CPP                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mmakboub <mmakboub@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/05/14 16:38:27 by mmakboub          #+#    #+#             */
/*   Updated: 2023/05/14 21:32:40 by mmakboub         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include<iostream>
#include<string.h>
#include<stdexcept>
#include<exception>
#include<vector>


//STL: standard template library 
//it contains libraries each library contain : a container(array as exemple) , iterator(intermediaire entre le conteneur et l algorithme) and algorithm(sort(), min(), max() as exemple)
//Un conteneur en programmation fait référence à une structure de données qui permet de stocker et d'organiser des éléments. Les conteneurs fournissent des opérations et des fonctionnalités pour ajouter, supprimer, rechercher et manipuler les éléments stockés.

//En général, les conteneurs sont utilisés pour regrouper des données de manière organisée afin de faciliter leur utilisation et leur manipulation dans un programme. Ils sont largement utilisés dans de nombreux langages de programmation, y compris C++, Java et Python, pour n'en citer que quelques-uns.

//Les conteneurs peuvent prendre différentes formes et offrir différentes fonctionnalités en fonction des besoins spécifiques.
