/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   INTRO.CPP                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mmakboub <mmakboub@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/05/14 16:38:27 by mmakboub          #+#    #+#             */
/*   Updated: 2023/05/14 16:44:17 by mmakboub         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include<iostream>
#include<string.h>
#include<stdexcept>
#include<exception>
#include<vector>


//STL: standard template library 
//it contains libraries each library contain : a container(array as exemple) , iterator(intermediaire entre le conteneur et l algorithme) and algorithm(sort(), min(), max() as exemple)
//
